minor visual indent fixes

diff --git a/quickemu b/quickemu
--- a/quickemu
+++ b/quickemu
@@ -235,7 +235,7 @@ function vm_boot() {
     local MAC_DISK_DEV="${MAC_DISK_DEV:-ide-hd,bus=ahci.2}"
     local NET_DEVICE="${NET_DEVICE:-virtio-net}"
     local OSK=""
-  local SOUND=""
+    local SOUND=""
     local SMM="${SMM:-off}"
     local USB_HOST_PASSTHROUGH_CONTROLLER="qemu-xhci"
     local VGA=""
@@ -254,7 +254,7 @@ function vm_boot() {
     echo "Quickemu ${VERSION} using ${QEMU} v${QEMU_VER_LONG}"
     echo " - Host:     ${LSB_DESCRIPTION} running ${KERNEL_NAME} ${KERNEL_VER} ${KERNEL_NODE}"
 
-  HOST_CPU_CORES=$(nproc)
+    HOST_CPU_CORES=$(nproc)
     HOST_CPU_MODEL=$(lscpu | grep '^Model name:' | cut -d':' -f2 | sed 's/  //g')
     HOST_CPU_SOCKETS=$(lscpu | grep -E 'Socket' | cut -d':' -f2 | sed 's/ //g')
     HOST_CPU_VENDOR=$(lscpu | grep -E 'Vendor' | cut -d':' -f2 | sed 's/ //g')
@@ -795,15 +795,15 @@ function vm_boot() {
     # Add fullscreen options
     VIDEO="${VGA} ${VIDEO} ${FULLSCREEN}"
 
-  # Build the sound hardware configuration
-  if [ "${SOUND_CARD}" == "intel-hda" ]; then
-    SOUND="-device intel-hda -device hda-duplex,audiodev=audio0"
-  elif [ "${SOUND_CARD}" == "ac97" ] || [ "${SOUND_CARD}" == "es1370" ] || [ "${SOUND_CARD}" == "sb16" ]; then
-    SOUND="-device ${SOUND_CARD},audiodev=audio0"
-  elif [ "${SOUND_CARD}" == "none" ]; then
-    SOUND=""
-  fi
-  echo " - Sound:    ${SOUND_CARD}"
+    # Build the sound hardware configuration
+    if [ "${SOUND_CARD}" == "intel-hda" ]; then
+        SOUND="-device intel-hda -device hda-duplex,audiodev=audio0"
+    elif [ "${SOUND_CARD}" == "ac97" ] || [ "${SOUND_CARD}" == "es1370" ] || [ "${SOUND_CARD}" == "sb16" ]; then
+        SOUND="-device ${SOUND_CARD},audiodev=audio0"
+    elif [ "${SOUND_CARD}" == "none" ]; then
+        SOUND=""
+    fi
+    echo " - Sound:    ${SOUND_CARD}"
 
     # Set the hostname of the VM
     local NET="user,hostname=${VMNAME}"
@@ -912,7 +912,7 @@ function vm_boot() {
     fi
 
     # If smbd is available and ~/Public is present export it to the guest via samba
-  if [[ -x "$(command -v smbd)" && -n ${PUBLIC} ]]; then
+    if [[ -x "$(command -v smbd)" && -n ${PUBLIC} ]]; then
         NET="${NET},smb=${PUBLIC}"
         echo " - smbd:     On guest: smb://10.0.2.4/qemu"
     fi
@@ -1244,12 +1244,12 @@ function vm_boot() {
         exit 1
     fi
 
-  if [ -z "${EXTRA_ARGS}" ]; then
-    EXTRA_ARGS="${extra_args}"
-  fi
-  if [ -n "${EXTRA_ARGS}" ]; then
-      args+=(${EXTRA_ARGS})
-  fi
+    if [ -z "${EXTRA_ARGS}" ]; then
+        EXTRA_ARGS="${extra_args}"
+    fi
+    if [ -n "${EXTRA_ARGS}" ]; then
+        args+=(${EXTRA_ARGS})
+    fi
 
     # The OSK parameter contains parenthesis, they need to be escaped in the shell
     # scripts. The vendor name, Quickemu Project, contains a space. It needs to be
@@ -1338,7 +1338,7 @@ function usage() {
     echo "  ${LAUNCHER} --vm ubuntu.conf"
     echo
     echo "You can also pass optional parameters"
-  echo "  --access                          : Enable remote spice access support. 'local' (default), 'remote', 'clientipaddress'"
+    echo "  --access                          : Enable remote spice access support. 'local' (default), 'remote', 'clientipaddress'"
     echo "  --braille                         : Enable braille support. Requires SDL."
     echo "  --delete-disk                     : Delete the disk image and EFI variables"
     echo "  --delete-vm                       : Delete the entire VM and it's configuration"
@@ -1356,7 +1356,7 @@ function usage() {
     echo "  --viewer <viewer>                 : Choose an alternative viewer. @Options: 'spicy' (default), 'remote-viewer', 'none'"
     echo "  --ssh-port <port>                 : Set ssh-port manually"
     echo "  --spice-port <port>               : Set spice-port manually"
-  echo "  --public-dir <path>               : Expose share directory. @Options: '' (default: xdg-user-dir PUBLICSHARE), '<directory>', 'none'"
+    echo "  --public-dir <path>               : Expose share directory. @Options: '' (default: xdg-user-dir PUBLICSHARE), '<directory>', 'none'"
     echo "  --monitor <type>                  : Set monitor connection type. @Options: 'socket' (default), 'telnet', 'none'"
     echo "  --monitor-telnet-host <ip/host>   : Set telnet host for monitor. (default: 'localhost')"
     echo "  --monitor-telnet-port <port>      : Set telnet port for monitor. (default: '4440')"
@@ -1368,7 +1368,7 @@ function usage() {
     echo "  --keyboard_layout <layout>        : Set keyboard layout."
     echo "  --mouse <type>                    : Set mouse. @Options: 'tablet' (default), 'ps2', 'usb', 'virtio'"
     echo "  --usb-controller <type>           : Set usb-controller. @Options: 'ehci' (default), 'xhci', 'none'"
-  echo "  --sound-card <type>               : Set sound card. @Options: 'intel-hda' (default), 'ac97', 'es1370', 'sb16', 'none'"
+    echo "  --sound-card <type>               : Set sound card. @Options: 'intel-hda' (default), 'ac97', 'es1370', 'sb16', 'none'"
     echo "  --extra_args <arguments>          : Pass additional arguments to qemu"
     echo "  --version                         : Print version"
     exit 1
@@ -1382,10 +1382,10 @@ function display_param_check() {
 }
 
 function sound_card_param_check() {
-  if [ "${SOUND_CARD}" != "intel-hda" ] && [ "${SOUND_CARD}" != "ac97" ] && [ "${SOUND_CARD}" != "es1370" ] && [ "${SOUND_CARD}" != "sb16" ] && [ "${SOUND_CARD}" != "none" ]; then
-    echo "ERROR! Requested sound card '${SOUND_CARD}' is not recognised."
-    exit 1
-  fi
+    if [ "${SOUND_CARD}" != "intel-hda" ] && [ "${SOUND_CARD}" != "ac97" ] && [ "${SOUND_CARD}" != "es1370" ] && [ "${SOUND_CARD}" != "sb16" ] && [ "${SOUND_CARD}" != "none" ]; then
+        echo "ERROR! Requested sound card '${SOUND_CARD}' is not recognised."
+        exit 1
+    fi
 }
 
 function viewer_param_check() {
@@ -1578,7 +1578,7 @@ if [ $# -lt 1 ]; then
 else
     while [ $# -gt 0 ]; do
         case "${1}" in
-          -access|--access)
+        -access|--access)
             ACCESS="${2}"
             shift
             shift;;
@@ -1813,10 +1813,10 @@ if [ -n "${VM}" ] && [ -e "${VM}" ]; then
         exit 1
     fi
 
-  if [ -z "${SOUND_CARD}" ]; then
-    SOUND_CARD="${sound_card}"
-  fi
-  sound_card_param_check
+    if [ -z "${SOUND_CARD}" ]; then
+        SOUND_CARD="${sound_card}"
+    fi
+    sound_card_param_check
 
     # Check if vm is already run
     VM_PID=0
@@ -1895,4 +1895,4 @@ fi
 
 [ -n "${MONITOR_CMD}" ] && monitor_send_cmd "${MONITOR_CMD}"
 
-# vim:tabstop=2:shiftwidth=2:expandtab
+# vim:tabstop=4:shiftwidth=4:expandtab
